---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    # ##########################################################################
    # Modules tso_command
    ############################################################################
    - name: Execute TSO commands to allocate a new dataset
      zos_tso_command:
          commands:
		       - RACDCERT ID(EE4QSTC) LISTRING(EE4QRING)